name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.11.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migration
        run: python manage.py migrate

      - name: Run Tests
        run: python manage.py test